### ISSUE TITLE
Nice lib

### ISSUE THREAD

**Issue by AndreiRegiani** [onrik/pyqiwi#1]
I see this is a new repository, is it functional already? How to test it? (Does QIWI provide developer accounts/server?) They have terrible docs, thanks for sharing your code. When you can add a demo/example code.

Cheers

**Comment by onrik** [comment]
Unit tests, examples and pypi package in progress. Lib ready for using in production. Unfortunately, QIWI doesn't provider test accounts. I tested code with real payments. I don't think that their docs is terrible (https://static.qiwi.com/en/doc/ishop/protocols/OnlineStoresProtocols_REST_EN.pdf)

**Comment by AndreiRegiani** [comment]
> Unit tests, examples and pypi package in progress

+1 Awesome

> I don't think that their docs is terrible

Thanks for the link, very helpful. I couldn't find it before, not being a Russian speaker it's hard to go through their website, which is Russian-only (language button does not work), so your library will be helpful.
